Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/8/2023
Var
numero, multiplicando, produto: inteiro


Inicio

   escreval("Digite o número: ")
   leia(numero)

   para multiplicando de 0 ate 10 faca
      produto <- numero * multiplicando

      escreva(produto)

   fimpara


Fimalgoritmo