Algoritmo "funcao dobro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/8/2023
Var
   numero, resultado: inteiro

funcao dobro (n : inteiro) : inteiro
Inicio
      retorne = n * 2
fimfuncao

inicio
escreval("Digite um numero: ")
leia (numero)

resultado <- dobro(numero)

escreval("O dobro é ", resultado)

Fimalgoritmo