Algoritmo "procedimento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/8/2023
Var
n: caractere

procedimento texto(nome: caractere)
inicio

escreval("Bom dia ", nome)

fimprocedimento
Inicio

escreval("Digite seu nome: ")
leia(n)
texto(n)


Fimalgoritmo